#!/usr/bin/env python3
"""Prepare Nova hybrid framework: prune shim duplicates and emit Soong exclude_srcs."""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]
NOVA_FW = ROOT / "vendor/nova/nova-framework"
SRC = NOVA_FW / "src"
BRIDGE_LIST = NOVA_FW / "bridge_files.txt"
AOSP_CORE = ROOT / "frameworks/base/core/java"
AOSP_GRAPHICS = ROOT / "frameworks/base/graphics/java"
AOSP_CORE_BP = ROOT / "frameworks/base/core/java/Android.bp"
AOSP_GRAPHICS_BP = ROOT / "frameworks/base/graphics/java/Android.bp"
NOVA_HYBRID_BEGIN = "// NOVA_HYBRID_FILEGROUP_BEGIN"
NOVA_HYBRID_END = "// NOVA_HYBRID_FILEGROUP_END"

AOSP_PACKAGES = [
    ("core", AOSP_CORE, [
        "android/view/**/*.java",
        "android/widget/**/*.java",
        "android/text/**/*.java",
        "android/animation/**/*.java",
        "android/util/**/*.java",
        "android/database/**/*.java",
        "android/net/**/*.java",
        "android/provider/**/*.java",
        "android/preference/**/*.java",
        "android/window/**/*.java",
        "com/android/internal/util/**/*.java",
        "com/android/internal/view/menu/**/*.java",
    ]),
    ("graphics", AOSP_GRAPHICS, [
        "**/*.java",
    ]),
]


def load_bridge_files() -> set[str]:
    keep: set[str] = set()
    for line in BRIDGE_LIST.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        keep.add(line)
    return keep


def glob_aosp_sources() -> list[str]:
    import glob

    paths: list[str] = []
    for _name, base, patterns in AOSP_PACKAGES:
        if not base.is_dir():
            continue
        for pattern in patterns:
            for path in sorted(base.glob(pattern)):
                if path.suffix != ".java":
                    continue
                rel = path.relative_to(base).as_posix()
                paths.append(rel)
    return sorted(set(paths))


def write_aosp_bp(bridge_files: set[str], aosp_sources: list[str]) -> None:
    core_excludes = sorted(
        rel for rel in aosp_sources if rel in bridge_files and (AOSP_CORE / rel).is_file()
    )
    graphics_excludes = sorted(
        set(
            rel
            for rel in aosp_sources
            if rel in bridge_files and (AOSP_GRAPHICS / rel).is_file()
        )
        | {"android/graphics/HardwareRenderer.java"}
    )

    header = [
        "// GENERATED by vendor/nova/nova-framework/tools/sync-hybrid-framework.py",
        "// Filegroups must live under frameworks/base so Soong globs resolve to real .java files.",
        "",
    ]

    # Per-package slices — enable incrementally in nova-framework/Android.bp (hybrid-fork Step 4).
    # Subsystems we stub in src/ — exclude from AOSP view glob (hybrid-fork Step 2).
    VIEW_AOSP_EXCLUDES = [
        "android/view/OrientationEventListener.java",
        "android/view/accessibility/**/*.java",
        "android/view/autofill/**/*.java",
        "android/view/contentcapture/**/*.java",
        "android/view/contentprotection/**/*.java",
        "android/view/displayhash/**/*.java",
        "android/view/inputmethod/**/*.java",
        "android/view/selectiontoolbar/**/*.java",
        "android/view/textclassifier/**/*.java",
        "android/view/textservice/**/*.java",
        "android/view/translation/**/*.java",
        "android/view/inspector/**/*.java",
        "android/view/ViewStub.java",
        "android/view/FocusFinder.java",
        "android/view/ViewStructure.java",
        "android/view/InputDevice.java",
        "android/view/InputWindowHandle.java",
        "android/view/InputChannel.java",
        "android/view/InputEvent.java",
        "android/view/InputMonitor.java",
        "android/view/InputQueue.java",
        "android/view/SurfaceView.java",
        # WMS / insets / display policy — Nova uses ViewRootImpl + Wayland, not AOSP WMS graph.
        "android/view/InsetsController.java",
        "android/view/InsetsAnimationControlImpl.java",
        "android/view/InsetsAnimationThreadControlRunner.java",
        "android/view/InsetsAnimationControlCallbacks.java",
        "android/view/InsetsAnimationControlRunner.java",
        "android/view/InsetsAnimationSpec.java",
        "android/view/InsetsAnimationThread.java",
        "android/view/InsetsSource.java",
        "android/view/InsetsSourceConsumer.java",
        "android/view/InsetsResizeAnimationRunner.java",
        "android/view/InsetsFlags.java",
        "android/view/InsetsFrameProvider.java",
        "android/view/InsetsState.java",
        "android/view/InsetsSourceControl.java",
        "android/view/PendingInsetsController.java",
        "android/view/InternalInsetsAnimationController.java",
        "android/view/WindowManagerImpl.java",
        "android/view/WindowManagerWrapper.java",
        "android/view/WindowManagerGlobal.java",
        "android/view/WindowManagerPolicyConstants.java",
        "android/view/WindowMetrics.java",
        "android/view/WindowMetricsController.java",
        "android/view/WindowRelayoutResult.java",
        "android/view/WindowLayout.java",
        "android/view/WindowlessWindowLayout.java",
        "android/view/WindowlessWindowManager.java",
        "android/view/AccessibilityEmbeddedConnection.java",
        "android/view/AccessibilityInteractionController.java",
        "android/view/AttachedSurfaceControl.java",
        "android/view/CrossWindowBlurListeners.java",
        "android/view/FrameMetricsObserver.java",
        "android/view/InputFilter.java",
        "android/view/NotificationHeaderView.java",
        "android/view/PrivacyIndicatorBounds.java",
        "android/view/RemoteAccessibilityController.java",
        "android/view/RemoteAnimationAdapter.java",
        "android/view/RemoteAnimationDefinition.java",
        "android/view/RemoteAnimationTarget.java",
        "android/view/ScreenRecordingCallbacks.java",
        "android/view/SurfaceControlActivePicture.java",
        "android/view/SurfaceControlActivePictureListener.java",
        "android/view/SurfaceControlRegistry.java",
        "android/view/SyncRtSurfaceTransactionApplier.java",
        "android/view/ScrollCaptureConnection.java",
        "android/view/ScrollCaptureCallback.java",
        "android/view/ScrollCaptureResponse.java",
        "android/view/ScrollCaptureSearchResults.java",
        "android/view/ScrollCaptureSession.java",
        "android/view/ScrollCaptureTarget.java",
        "android/view/DisplayInfo.java",
        "android/view/DisplayShape.java",
        "android/view/DisplayCutout.java",
        "android/view/DisplayAddress.java",
        "android/view/DisplayAdjustments.java",
        "android/view/DisplayEventReceiver.java",
        "android/view/Display.java",
        "android/view/ContentRecordingSession.java",
        "android/view/GestureDetector.java",
        "android/view/TextureView.java",
        "android/view/SurfaceControl.java",
        "android/view/SurfaceControlHdrLayerInfoListener.java",
        "android/view/SurfaceControlViewHost.java",
        "android/view/SurfaceSession.java",
        "android/view/SurfaceHolder.java",
        "android/view/FrameMetrics.java",
        "android/view/HardwareRenderer.java",
        "android/view/ThreadedRenderer.java",
        "android/view/RenderNodeAnimator.java",
        "android/view/NativeVectorDrawableAnimator.java",
        "android/view/ImeBackAnimationController.java",
        "android/view/ImeFocusController.java",
        "android/view/HandwritingInitiator.java",
        "android/view/PixelCopy.java",
        "android/view/TouchDelegate.java",
        "android/view/VerifiedKeyEvent.java",
        "android/view/VerifiedMotionEvent.java",
        "android/view/ViewFrameInfo.java",
        "android/view/ViewProtoLogGroups.java",
        "android/view/ViewRootInsetsControllerHost.java",
        "android/view/VelocityTracker.java",
        "android/view/WindowId.java",
        "android/view/WindowInfo.java",
        "android/view/XrWindowProperties.java",
        "android/view/PointerIcon.java",
        "android/view/InputEventReceiver.java",
        "android/view/InputEventSender.java",
        "android/view/BatchedInputEventReceiver.java",

        "android/view/AppTransitionAnimationSpec.java",
        "android/view/CompositionSamplingListener.java",
        "android/view/ContentInfo.java",
        "android/view/ContextThemeWrapper.java",
        "android/view/DragAndDropPermissions.java",
        "android/view/DragEvent.java",
        "android/view/FocusFinderHelper.java",
        "android/view/HdrRenderState.java",
        "android/view/InputEventAssigner.java",
        "android/view/KeyCharacterMap.java",
        "android/view/KeyboardShortcutInfo.java",
        "android/view/Menu.java",
        "android/view/MenuItem.java",
        "android/view/NotificationTopLineView.java",
        "android/view/OrientationListener.java",
        "android/view/RoundedCorners.java",
        "android/view/ScaleGestureDetector.java",
        "android/view/ScrollFeedbackProvider.java",
        "android/view/ViewAnimationHostBridge.java",
        "android/view/ViewAnimationUtils.java",
        "android/view/ViewConfiguration.java",
        "android/view/ViewOverlay.java",
        "android/view/ViewPropertyAnimator.java",
        "android/view/ViewRootRectTracker.java",
        "android/view/WindowInsets.java",
        "android/view/WindowInsetsAnimationController.java",
        "android/view/WindowInsetsAnimationControlListener.java",
        "android/view/CutoutSpecification.java",
        "android/view/ViewGroupOverlay.java",
        "android/view/animation/AccelerateInterpolator.java",
        "android/view/animation/Animation.java",
        "android/view/animation/AnimationUtils.java",
        "android/view/animation/AnimationSet.java",
        "android/view/animation/ExtendAnimation.java",
        "android/view/animation/AnticipateInterpolator.java",
        "android/view/animation/CycleInterpolator.java",
        "android/view/animation/DecelerateInterpolator.java",
        "android/view/animation/GridLayoutAnimationController.java",
        "android/view/animation/LayoutAnimationController.java",
        "android/view/animation/OvershootInterpolator.java",
        "android/view/animation/AlphaAnimation.java",
        "android/view/animation/ClipRectAnimation.java",
        "android/view/animation/PathInterpolator.java",
        "android/view/animation/RotateAnimation.java",
        "android/view/animation/ScaleAnimation.java",
        "android/view/animation/TranslateAnimation.java",
        "android/view/animation/TranslateXAnimation.java",
        "android/view/animation/TranslateYAnimation.java",
        "android/view/input/InputEventCompatHandler.java",
        "android/view/input/LetterboxScrollProcessor.java",
        "android/view/input/MouseToTouchProcessor.java",
        "android/view/input/StylusButtonCompatibility.java",
    ]

    WIDGET_EXTRA_EXCLUDES = [
        "android/widget/Editor.java",
        "android/widget/Magnifier.java",
        "android/widget/PopupWindow.java",
        "android/widget/RemoteViews.java",
        "android/widget/RemoteViewsAdapter.java",
        "android/widget/RemoteViewsService.java",
        "android/widget/Toast.java",
        "android/widget/ToastPresenter.java",
        "android/widget/VideoView.java",
        "android/widget/DropDownListView.java",
        "android/widget/ExpandableListView.java",
        "android/widget/HorizontalScrollView.java",
        "android/widget/NumberPicker.java",
        "android/widget/ProgressBar.java",
        "android/widget/RadialTimePickerView.java",
        "android/widget/RadioGroup.java",
        "android/widget/ScrollView.java",
        "android/widget/SearchView.java",
        "android/widget/SelectionActionModeHelper.java",
        "android/widget/SimpleMonthView.java",
        "android/widget/TabHost.java",
        "android/widget/TableLayout.java",
        "android/widget/TableRow.java",
        "android/widget/TimePicker.java",
        "android/widget/TimePickerClockDelegate.java",
        "android/widget/Toolbar.java",
        "android/widget/DifferentialMotionFlingHelper.java",
        "android/widget/inline/InlineContentView.java",
        "android/widget/AdapterViewAnimator.java",
        "android/widget/CompoundButton.java",
        "android/widget/GridView.java",
        "android/widget/ListView.java",
        "android/widget/Switch.java",
        "android/widget/ImageView.java",
        "android/widget/AbsListView.java",
        "android/widget/AbsSpinner.java",
        "android/widget/AccessibilityIterators.java",
        "android/widget/ActionMenuPresenter.java",
        "android/widget/ActionMenuView.java",
        "android/widget/ActivityChooserModel.java",
        "android/widget/ActivityChooserView.java",
        "android/widget/AdapterView.java",
        "android/widget/CheckedTextView.java",
        "android/widget/DatePicker.java",
        "android/widget/DateTimeView.java",
        "android/widget/DayPickerPagerAdapter.java",
        "android/widget/DayPickerView.java",
        "android/widget/DayPickerViewPager.java",
        "android/widget/ListPopupWindow.java",
        "android/widget/MenuPopupWindow.java",
        "android/widget/RemoteCollectionItemsAdapter.java",
        "android/widget/TimePickerSpinnerDelegate.java",
        "android/widget/CalendarViewMaterialDelegate.java",
        "android/widget/DatePickerCalendarDelegate.java",
        "android/widget/DatePickerSpinnerDelegate.java",
        "android/widget/ShareActionProvider.java",
        "android/widget/SmartSelectSprite.java",
        "android/widget/Spinner.java",
        "android/widget/PopupMenu.java",

        "android/widget/AbsSeekBar.java",
        "android/widget/AbsoluteLayout.java",
        "android/widget/AdapterViewFlipper.java",
        "android/widget/AnalogClock.java",
        "android/widget/AppSecurityPermissions.java",
        "android/widget/ArrayAdapter.java",
        "android/widget/AutoCompleteTextView.java",
        "android/widget/CalendarView.java",
        "android/widget/CalendarViewLegacyDelegate.java",
        "android/widget/Chronometer.java",
        "android/widget/DialerFilter.java",
        "android/widget/EdgeEffect.java",
        "android/widget/EditorTouchState.java",
        "android/widget/ExpandableListConnector.java",
        "android/widget/FastScroller.java",
        "android/widget/ForwardingListener.java",
        "android/widget/Gallery.java",
        "android/widget/GridLayout.java",
        "android/widget/ImageButton.java",
        "android/widget/ImeAwareEditText.java",
        "android/widget/MediaController.java",
        "android/widget/MultiAutoCompleteTextView.java",
        "android/widget/QuickContactBadge.java",
        "android/widget/RadioButton.java",
        "android/widget/RatingBar.java",
        "android/widget/RelativeLayout.java",
        "android/widget/RemoteViewsSerializers.java",
        "android/widget/SeekBar.java",
        "android/widget/SlidingDrawer.java",
        "android/widget/SpellChecker.java",
        "android/widget/StackView.java",
        "android/widget/SuggestionsAdapter.java",
        "android/widget/TabWidget.java",
        "android/widget/TextClock.java",
        "android/widget/TextInputTimePickerView.java",
        "android/widget/TextViewOnReceiveContentListener.java",
        "android/widget/TextViewTranslationCallback.java",
        "android/widget/ToggleButton.java",
        "android/widget/TwoLineListItem.java",
        "android/widget/ViewAnimator.java",
        "android/widget/ViewFlipper.java",
        "android/widget/YearPickerView.java",
        "android/widget/ZoomButton.java",
        "android/widget/ZoomButtonsController.java",
        "android/widget/ZoomControls.java",
        "android/widget/inline/InlinePresentationSpec.java",
        "android/widget/DigitalClock.java",
        "android/widget/OverScroller.java",
        "android/widget/Scroller.java",
        "android/widget/ViewSwitcher.java",
    ]

    TEXT_EXTRA_EXCLUDES = [
        "android/text/Html.java",
        "android/text/Layout.java",
        "android/text/TextLine.java",
        "android/text/format/Time.java",
        "android/text/format/TimeFormatter.java",
        "android/text/style/RasterizerSpan.java",
        "android/text/style/StyleSpan.java",
        "android/text/DynamicLayout.java",
        "android/text/MeasuredParagraph.java",
        "android/text/PrecomputedText.java",
        "android/text/StaticLayout.java",

        "android/text/AndroidBidi.java",
        "android/text/AutoGrowArray.java",
        "android/text/AutoText.java",
        "android/text/BoringLayout.java",
        "android/text/FontConfig.java",
        "android/text/GraphemeClusterSegmentFinder.java",
        "android/text/SpannableStringBuilder.java",
        "android/text/SpannableStringInternal.java",
        "android/text/TextPaint.java",
        "android/text/TextShaper.java",
        "android/text/TextUtils.java",
        "android/text/format/DateFormat.java",
        "android/text/format/DateIntervalFormat.java",
        "android/text/format/DateUtils.java",
        "android/text/format/Formatter.java",
        "android/text/format/TimeMigrationUtils.java",
        "android/text/method/AllCapsTransformationMethod.java",
        "android/text/method/ArrowKeyMovementMethod.java",
        "android/text/method/BaseKeyListener.java",
        "android/text/method/BaseMovementMethod.java",
        "android/text/method/CharacterPickerDialog.java",
        "android/text/method/DateKeyListener.java",
        "android/text/method/DateTimeKeyListener.java",
        "android/text/method/DialerKeyListener.java",
        "android/text/method/DigitsKeyListener.java",
        "android/text/method/InsertModeTransformationMethod.java",
        "android/text/method/LinkMovementMethod.java",
        "android/text/method/MetaKeyKeyListener.java",
        "android/text/method/QwertyKeyListener.java",
        "android/text/method/ScrollingMovementMethod.java",
        "android/text/method/TextKeyListener.java",
        "android/text/method/TimeKeyListener.java",
        "android/text/method/Touch.java",
        "android/text/style/AccessibilityClickableSpan.java",
        "android/text/style/BulletSpan.java",
        "android/text/style/ClickableSpan.java",
        "android/text/style/DynamicDrawableSpan.java",
        "android/text/style/EasyEditSpan.java",
        "android/text/style/ImageSpan.java",
        "android/text/style/LineBreakConfigSpan.java",
        "android/text/style/LineHeightSpan.java",
        "android/text/style/LocaleSpan.java",
        "android/text/style/MaskFilterSpan.java",
        "android/text/style/QuoteSpan.java",
        "android/text/style/ScaleXSpan.java",
        "android/text/style/SpanUtils.java",
        "android/text/style/StrikethroughSpan.java",
        "android/text/style/SuggestionSpan.java",
        "android/text/style/TextAppearanceSpan.java",
        "android/text/style/TtsSpan.java",
        "android/text/style/TypefaceSpan.java",
        "android/text/style/UnderlineSpan.java",
        "android/text/util/Linkify.java",
        "android/text/SpannableString.java",
        "android/text/SpannedString.java",
        "android/text/style/AccessibilityURLSpan.java",
        "android/text/Annotation.java",
        "android/text/InputFilter.java",
        "android/text/method/MultiTapKeyListener.java",
        "android/text/method/NumberKeyListener.java",
        "android/text/method/PasswordTransformationMethod.java",
        "android/text/method/WordIterator.java",
        "android/text/style/AbsoluteSizeSpan.java",
        "android/text/style/AccessibilityReplacementSpan.java",
        "android/text/style/AlignmentSpan.java",
        "android/text/style/BackgroundColorSpan.java",
        "android/text/style/ForegroundColorSpan.java",
        "android/text/style/LeadingMarginSpan.java",
        "android/text/style/LineBackgroundSpan.java",
        "android/text/style/NoWritingToolsSpan.java",
        "android/text/style/RelativeSizeSpan.java",
        "android/text/style/SpellCheckSpan.java",
        "android/text/style/SubscriptSpan.java",
        "android/text/style/SuggestionRangeSpan.java",
        "android/text/style/SuperscriptSpan.java",
        "android/text/style/URLSpan.java",
        "android/text/WordSegmentFinder.java",
    ]

    INTERNAL_UTIL_EXTRA_EXCLUDES = [
        "com/android/internal/util/ArtBinaryXmlPullParser.java",
        "com/android/internal/util/ArtBinaryXmlSerializer.java",
        "com/android/internal/util/ArtFastDataInput.java",
        "com/android/internal/util/ArtFastDataOutput.java",
        "com/android/internal/util/AnnotationValidations.java",
        "com/android/internal/util/LatencyTracker.java",
        "com/android/internal/util/ContrastColorUtil.java",
        "com/android/internal/util/AsyncChannel.java",
        "com/android/internal/util/DumpUtils.java",
        "com/android/internal/util/MimeIconUtils.java",
        "com/android/internal/util/ProgressReporter.java",
        "com/android/internal/util/ScreenshotHelper.java",
        "com/android/internal/util/ScreenshotRequest.java",
        "com/android/internal/util/SyncResultReceiver.java",
        "com/android/internal/util/CollectionUtils.java",
        "com/android/internal/util/ConcurrentUtils.java",
        "com/android/internal/util/dump/DumpUtils.java",
        "com/android/internal/util/EmergencyAffordanceManager.java",
        "com/android/internal/util/ExponentiallyBucketedHistogram.java",
        "com/android/internal/util/function/pooled/PooledLambdaImpl.java",
        "com/android/internal/util/function/pooled/PooledLambda.java",
        "com/android/internal/util/ImageUtils.java",
        "com/android/internal/util/LocalLog.java",
        "com/android/internal/util/MemInfoReader.java",
        "com/android/internal/util/NamedLock.java",
        "com/android/internal/util/NotificationMessagingUtil.java",
        "com/android/internal/util/ObservableServiceConnection.java",
        "com/android/internal/util/Parcelling.java",
        "com/android/internal/util/PerfettoTrigger.java",
        "com/android/internal/util/RingBuffer.java",
        "com/android/internal/util/SettingsWrapper.java",
        "com/android/internal/util/StatLogger.java",
        "com/android/internal/util/StringCache.java",
        "com/android/internal/util/TokenBucket.java",
        "com/android/internal/util/UserIcons.java",
        "com/android/internal/util/VibrationStatsWriter.java",
        "com/android/internal/util/BitUtils.java",
        "com/android/internal/util/FunctionalUtils.java",
        "com/android/internal/util/DataClass.java",
        "com/android/internal/util/PersistentServiceConnection.java",
        "com/android/internal/util/function/pooled/OmniFunction.java",
        "com/android/internal/util/function/pooled/PooledSupplier.java",
        "com/android/internal/util/function/pooled/PooledPredicate.java",
        "com/android/internal/util/function/pooled/PooledRunnable.java",
    ]

    UTIL_EXTRA_EXCLUDES = [
        "android/util/JsonReader.java",
        "android/util/IntArray.java",
        "android/util/LongArray.java",
        "android/util/LongSparseArray.java",
        "android/util/LongSparseLongArray.java",
        "android/util/NtpTrustedTime.java",
        "android/util/Size.java",
        "android/util/Xml.java",
        "android/util/CloseGuard.java",
        "android/util/MemoryIntArray.java",
        "android/util/jar/StrictJarFile.java",
        "android/util/jar/StrictJarVerifier.java",
        "android/util/apk/**/*.java",
        "android/util/TimeUtils.java",
        "android/util/EventLog_ravenwood.java",
        "android/util/Log_ravenwood.java",
        "android/util/SystemConfigFileCommitEventLogger.java",
        "android/util/Property.java",
        "android/util/DisplayMetrics.java",
        "android/util/FastMath.java",
        "android/util/Log.java",
        "android/util/MergedConfiguration.java",
        "android/util/Pools.java",

        "android/util/ArrayMap.java",
        "android/util/AtomicFile.java",
        "android/util/CharsetUtils.java",
        "android/util/DisplayUtils.java",
        "android/util/EventLog.java",
        "android/util/ExceptionUtils.java",
        "android/util/HashedStringCache.java",
        "android/util/IconDrawableFactory.java",
        "android/util/LauncherIcons.java",
        "android/util/LruCache.java",
        "android/util/PackageUtils.java",
        "android/util/PathParser.java",
        "android/util/RotationUtils.java",
        "android/util/SafetyProtectionUtils.java",
        "android/util/SizeF.java",
        "android/util/Slog.java",
        "android/util/SparseBooleanArray.java",
        "android/util/StateSet.java",
        "android/util/TimingsTraceLog.java",
        "android/util/TypedValue.java",
        "android/util/proto/ProtoInputStream.java",
        "android/util/proto/ProtoUtils.java",
    ]

    MENU_EXTRA_EXCLUDES = [
        "com/android/internal/view/menu/ActionMenuItemView.java",
        "com/android/internal/view/menu/CascadingMenuPopup.java",
        "com/android/internal/view/menu/ExpandedMenuView.java",
        "com/android/internal/view/menu/IconMenuItemView.java",
        "com/android/internal/view/menu/IconMenuView.java",
        "com/android/internal/view/menu/StandardMenuPopup.java",
        "com/android/internal/view/menu/SubMenuBuilder.java",
        "com/android/internal/view/menu/BaseMenuPresenter.java",
        "com/android/internal/view/menu/IconMenuPresenter.java",
        "com/android/internal/view/menu/ListMenuPresenter.java",
        "com/android/internal/view/menu/MenuItemImpl.java",
        "com/android/internal/view/menu/MenuPresenter.java",
        "com/android/internal/view/menu/ListMenuItemView.java",
        "com/android/internal/view/menu/MenuAdapter.java",
        "com/android/internal/view/menu/MenuDialogHelper.java",
        "com/android/internal/view/menu/MenuHelper.java",
        "com/android/internal/view/menu/MenuPopupHelper.java",
        "com/android/internal/view/menu/MenuPopup.java",
        "com/android/internal/view/menu/MenuView.java",
        "com/android/internal/view/menu/ContextMenuBuilder.java",

        "com/android/internal/view/menu/ActionMenu.java",
    ]

    WINDOW_EXTRA_EXCLUDES = [
        "android/window/BackAnimationAdapter.java",
        "android/window/BackNavigationInfo.java",
        "android/window/BackProgressAnimator.java",
        "android/window/DisplayAreaOrganizer.java",
        "android/window/DisplayWindowPolicyController.java",
        "android/window/ImeBackCallbackProxy.java",
        "android/window/ImeBackCallbackSender.java",
        "android/window/OnBackInvokedCallbackInfo.java",
        "android/window/PictureInPictureSurfaceTransaction.java",
        "android/window/RemoteTransition.java",
        "android/window/RemoteTransitionStub.java",
        "android/window/ScreenCapture.java",
        "android/window/SnapshotDrawerUtils.java",
        "android/window/StartingWindowInfo.java",
        "android/window/SurfaceSyncGroup.java",
        "android/window/SystemPerformanceHinter.java",
        "android/window/SystemUiContext.java",
        "android/window/TaskAppearedInfo.java",
        "android/window/TaskFpsCallback.java",
        "android/window/TaskFragmentCreationParams.java",
        "android/window/TaskFragmentInfo.java",
        "android/window/TaskFragmentOrganizer.java",
        "android/window/TaskFragmentOrganizerToken.java",
        "android/window/TaskFragmentParentInfo.java",
        "android/window/TaskOrganizer.java",
        "android/window/TaskSnapshot.java",
        "android/window/TaskSnapshotListenerTracker.java",
        "android/window/TaskSnapshotManager.java",
        "android/window/TransitionFilter.java",
        "android/window/TransitionInfo.java",
        "android/window/TransitionMetrics.java",
        "android/window/TransitionRequestInfo.java",
        "android/window/WindowContainerToken.java",
        "android/window/WindowContainerTransactionCallback.java",
        "android/window/WindowContainerTransaction.java",
        "android/window/WindowContextController.java",
        "android/window/WindowContext.java",
        "android/window/WindowInfosListenerForTest.java",
        "android/window/WindowInfosListener.java",
        "android/window/WindowOnBackInvokedDispatcher.java",
        "android/window/WindowOrganizer.java",
        "android/window/WindowProvider.java",
        "android/window/WindowProviderService.java",
        "android/window/WindowTokenClientController.java",
        "android/window/WindowTokenClient.java",
        "android/window/DisplayAreaInfo.java",
        "android/window/ProxyOnBackInvokedDispatcher.java",
        "android/window/ScreenCaptureInternal.java",
        "android/window/TaskFragmentOperation.java",
        "android/window/TaskFragmentTransaction.java",
        "android/window/TaskSnapshotListener.java",
        "android/window/DisplayAreaAppearedInfo.java",

        "android/window/ActivityTransitionInfo.java",
        "android/window/ActivityWindowInfo.java",
        "android/window/AppCompatTransitionInfo.java",
        "android/window/BackMotionEvent.java",
        "android/window/ConfigurationChangeSetting.java",
        "android/window/ConfigurationHelper.java",
        "android/window/DesktopExperienceFlags.java",
        "android/window/DesktopModeFlags.java",
        "android/window/SizeConfigurationBuckets.java",
        "android/window/SplashScreen.java",
        "android/window/SplashScreenView.java",
        "android/window/StartingWindowRemovalInfo.java",
        "android/window/SystemOnBackInvokedCallbacks.java",
        "android/window/TaskFragmentAnimationParams.java",
        "android/window/WindowBase.java",
        "android/window/WindowContextInfo.java",
        "android/window/WindowMetricsController.java",
        "android/window/BackEvent.java",
        "android/window/BackTouchTracker.java",
    ]

    ANIMATION_EXTRA_EXCLUDES = [
        "android/animation/RevealAnimator.java",
        "android/animation/LayoutTransition.java",
        "android/animation/AnimationHandler.java",
        "android/animation/Animator.java",
        "android/animation/AnimatorInflater.java",
        "android/animation/AnimatorSet.java",
        "android/animation/ObjectAnimator.java",
        "android/animation/ValueAnimator.java",
        "android/animation/PropertyValuesHolder.java",
        "android/animation/StateListAnimator.java",
        "android/animation/TimeAnimator.java",
    ]

    GRAPHICS_LITE_SRCS = [
        "android/graphics/Point.java",
        "android/graphics/PointF.java",
        "android/graphics/Matrix.java",
        "android/graphics/Outline.java",
        "android/graphics/PorterDuff.java",
        "android/graphics/Xfermode.java",
        "android/graphics/PixelFormat.java",
        "android/graphics/animation/HasNativeInterpolator.java",
        "android/graphics/animation/NativeInterpolator.java",
        "android/graphics/animation/NativeInterpolatorFactory.java",
    ]
    # Drawable classes are Nova bridges (src/), NOT AOSP.
    # AOSP drawables need full R.attr / R.styleable resource infrastructure
    # which Nova's lightweight resource bridge does not provide.

    SLICES = [
        ("nova-hybrid-animation-sources", ["android/animation/**/*.java"]),
        ("nova-hybrid-internal-util-sources", ["com/android/internal/util/**/*.java"]),
        ("nova-hybrid-internal-menu-sources", ["com/android/internal/view/menu/**/*.java"]),
        ("nova-hybrid-text-sources", ["android/text/**/*.java"]),
        ("nova-hybrid-widget-sources", ["android/widget/**/*.java"]),
        ("nova-hybrid-view-sources", ["android/view/**/*.java"]),
        ("nova-hybrid-window-sources", ["android/window/**/*.java"]),
        ("nova-hybrid-database-sources", ["android/database/**/*.java"]),
        ("nova-hybrid-net-sources", ["android/net/**/*.java"]),
        ("nova-hybrid-provider-sources", ["android/provider/**/*.java"]),
        ("nova-hybrid-preference-sources", ["android/preference/**/*.java"]),
        ("nova-hybrid-util-sources", ["android/util/**/*.java"]),
    ]

    def pattern_prefix(pattern: str) -> str:
        return pattern.split("*")[0].rstrip("/")

    def prefix_excludes(patterns: list[str]) -> list[str]:
        prefixes = [pattern_prefix(p) for p in patterns]
        out: list[str] = []
        for rel in core_excludes:
            if any(rel == p or rel.startswith(p + "/") for p in prefixes):
                out.append(rel)
        return sorted(out)

    def core_filegroup(name: str, patterns: list[str], excludes: list[str]) -> list[str]:
        lines = header + [
        "filegroup {",
            f'    name: "{name}",',
            '    visibility: ["//vendor:__subpackages__"],',
        "    srcs: [",
        ]
        for pattern in patterns:
            lines.append(f'        "{pattern}",')
        lines.extend(["    ],", "    exclude_srcs: ["])
        for rel in excludes:
            lines.append(f'        "{rel}",')
        lines.extend(["    ],", "}", ""])
        return lines

    core_lines: list[str] = []
    for slice_name, patterns in SLICES:
        excludes = prefix_excludes(patterns)
        if slice_name == "nova-hybrid-view-sources":
            excludes = sorted(set(excludes) | set(VIEW_AOSP_EXCLUDES))
        if slice_name == "nova-hybrid-internal-util-sources":
            excludes = sorted(set(excludes) | set(INTERNAL_UTIL_EXTRA_EXCLUDES))
        if slice_name == "nova-hybrid-internal-menu-sources":
            excludes = sorted(set(excludes) | set(MENU_EXTRA_EXCLUDES))
        if slice_name == "nova-hybrid-util-sources":
            excludes = sorted(set(excludes) | set(UTIL_EXTRA_EXCLUDES))
        if slice_name == "nova-hybrid-animation-sources":
            excludes = sorted(set(excludes) | set(ANIMATION_EXTRA_EXCLUDES))
        if slice_name == "nova-hybrid-widget-sources":
            excludes = sorted(set(excludes) | set(WIDGET_EXTRA_EXCLUDES))
        if slice_name == "nova-hybrid-text-sources":
            excludes = sorted(set(excludes) | set(TEXT_EXTRA_EXCLUDES))
        if slice_name == "nova-hybrid-window-sources":
            excludes = sorted(set(excludes) | set(WINDOW_EXTRA_EXCLUDES))
        core_lines += core_filegroup(slice_name, patterns, excludes)

    graphics_lines = header + [
        "filegroup {",
        '    name: "nova-hybrid-graphics-sources",',
        '    visibility: ["//vendor:__subpackages__"],',
        '    srcs: ["**/*.java"],',
        "    exclude_srcs: [",
    ]
    for rel in graphics_excludes:
        graphics_lines.append(f'        "{rel}",')
    graphics_lines.extend(["    ],", "}", ""])
    graphics_lines += header + [
        "filegroup {",
        '    name: "nova-hybrid-graphics-lite-sources",',
        '    visibility: ["//vendor:__subpackages__"],',
        "    srcs: [",
    ]
    for rel in GRAPHICS_LITE_SRCS:
        graphics_lines.append(f'        "{rel}",')
    graphics_lite_excludes = [rel for rel in graphics_excludes if rel in GRAPHICS_LITE_SRCS]
    graphics_lines.extend(["    ],", "    exclude_srcs: ["])
    for rel in sorted(graphics_lite_excludes):
        graphics_lines.append(f'        "{rel}",')
    graphics_lines.extend(["    ],", "}", ""])

    def strip_legacy_hybrid_blocks(text: str) -> str:
        marker = "// GENERATED by vendor/nova/nova-framework/tools/sync-hybrid-framework.py"
        while marker in text:
            start = text.find(marker)
            fg = text.find("filegroup {", start)
            if fg < 0:
                break
            depth = 0
            i = fg
            while i < len(text):
                if text[i : i + 1] == "{":
                    depth += 1
                elif text[i : i + 1] == "}":
                    depth -= 1
                    if depth == 0:
                        i += 1
                        break
                i += 1
            text = text[:start] + text[i:]
        if NOVA_HYBRID_BEGIN in text and NOVA_HYBRID_END in text:
            begin = text.find(NOVA_HYBRID_BEGIN)
            end = text.find(NOVA_HYBRID_END)
            if end > begin:
                text = text[:begin] + text[end + len(NOVA_HYBRID_END) + 1 :]
        return text

    def splice_into_android_bp(path: Path, block: list[str]) -> None:
        text = strip_legacy_hybrid_blocks(path.read_text())
        block_text = NOVA_HYBRID_BEGIN + "\n" + "\n".join(block) + "\n" + NOVA_HYBRID_END + "\n"
        text = text.rstrip() + "\n\n" + block_text
        path.write_text(text)

    splice_into_android_bp(AOSP_CORE_BP, core_lines)
    splice_into_android_bp(AOSP_GRAPHICS_BP, graphics_lines)


def prune_shims(bridge_files: set[str], dry_run: bool) -> int:
    removed = 0
    aosp_relpaths = set(glob_aosp_sources())
    for path in sorted(SRC.rglob("*.java")):
        rel = path.relative_to(SRC).as_posix()
        if rel in bridge_files:
            continue
        if rel not in aosp_relpaths:
            continue
        if dry_run:
            print(f"would remove {rel}")
        else:
            path.unlink()
            removed += 1
    return removed


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--prune", action="store_true", help="Delete superseded shim files")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    bridge = load_bridge_files()
    aosp = glob_aosp_sources()
    write_aosp_bp(bridge, aosp)
    print(
        f"Wrote {AOSP_CORE_BP.name} and {AOSP_GRAPHICS_BP.name} "
        f"({len(aosp)} AOSP sources, {sum(1 for x in aosp if x in bridge)} excludes)"
    )

    if args.prune:
        n = prune_shims(bridge, args.dry_run)
        print(f"{'Would remove' if args.dry_run else 'Removed'} {n} shim files")


if __name__ == "__main__":
    main()
