#!/usr/bin/env python3
"""Prepare Nova hybrid framework: prune shim duplicates and emit Soong exclude_srcs."""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]
NOVA_FW = ROOT / "vendor/nova/nova-framework"
SRC = NOVA_FW / "src"
BRIDGE_LIST = NOVA_FW / "bridge_files.txt"
AOSP_CORE = ROOT / "frameworks/base/core/java"
AOSP_GRAPHICS = ROOT / "frameworks/base/graphics/java"
AOSP_CORE_BP = ROOT / "frameworks/base/core/java/Android.bp"
AOSP_GRAPHICS_BP = ROOT / "frameworks/base/graphics/java/Android.bp"
NOVA_HYBRID_BEGIN = "// NOVA_HYBRID_FILEGROUP_BEGIN"
NOVA_HYBRID_END = "// NOVA_HYBRID_FILEGROUP_END"

AOSP_PACKAGES = [
    ("core", AOSP_CORE, [
        "android/view/**/*.java",
        "android/widget/**/*.java",
        "android/text/**/*.java",
        "android/animation/**/*.java",
        "android/util/**/*.java",
        "android/database/**/*.java",
        "android/net/**/*.java",
        "android/provider/**/*.java",
        "android/preference/**/*.java",
        "android/window/**/*.java",
        "com/android/internal/util/**/*.java",
        "com/android/internal/view/menu/**/*.java",
    ]),
    ("graphics", AOSP_GRAPHICS, [
        "**/*.java",
    ]),
]


def load_bridge_files() -> set[str]:
    keep: set[str] = set()
    for line in BRIDGE_LIST.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        keep.add(line)
    return keep


def glob_aosp_sources() -> list[str]:
    import glob

    paths: list[str] = []
    for _name, base, patterns in AOSP_PACKAGES:
        if not base.is_dir():
            continue
        for pattern in patterns:
            for path in sorted(base.glob(pattern)):
                if path.suffix != ".java":
                    continue
                rel = path.relative_to(base).as_posix()
                paths.append(rel)
    return sorted(set(paths))


def write_aosp_bp(bridge_files: set[str], aosp_sources: list[str]) -> None:
    core_excludes = sorted(
        rel for rel in aosp_sources if rel in bridge_files and (AOSP_CORE / rel).is_file()
    )
    graphics_excludes = sorted(
        set(
            rel
            for rel in aosp_sources
            if rel in bridge_files and (AOSP_GRAPHICS / rel).is_file()
        )
        | {"android/graphics/HardwareRenderer.java"}
    )

    header = [
        "// GENERATED by vendor/nova/nova-framework/tools/sync-hybrid-framework.py",
        "// Filegroups must live under frameworks/base so Soong globs resolve to real .java files.",
        "",
    ]

    core_patterns = []
    util_patterns = []
    for _name, _base, patterns in AOSP_PACKAGES:
        if _name != "core":
            continue
        for pattern in patterns:
            if pattern.startswith("android/util/"):
                util_patterns.append(pattern)
            else:
                core_patterns.append(pattern)

    def core_filegroup(name: str, patterns: list[str], excludes: list[str]) -> list[str]:
        lines = header + [
            "filegroup {",
            f'    name: "{name}",',
            '    visibility: ["//vendor:__subpackages__"],',
            "    srcs: [",
        ]
        for pattern in patterns:
            lines.append(f'        "{pattern}",')
        lines.extend(["    ],", "    exclude_srcs: ["])
        for rel in excludes:
            lines.append(f'        "{rel}",')
        lines.extend(["    ],", "}", ""])
        return lines

    core_excludes_all = core_excludes
    util_excludes = [rel for rel in core_excludes if rel.startswith("android/util/")]
    core_excludes_nonutil = [rel for rel in core_excludes if not rel.startswith("android/util/")]

    core_lines = core_filegroup("nova-hybrid-core-sources", core_patterns, core_excludes_nonutil)
    core_lines += core_filegroup("nova-hybrid-util-sources", util_patterns, util_excludes)

    graphics_lines = header + [
        "filegroup {",
        '    name: "nova-hybrid-graphics-sources",',
        '    visibility: ["//vendor:__subpackages__"],',
        '    srcs: ["**/*.java"],',
        "    exclude_srcs: [",
    ]
    for rel in graphics_excludes:
        graphics_lines.append(f'        "{rel}",')
    graphics_lines.extend(["    ],", "}", ""])

    def strip_legacy_hybrid_blocks(text: str) -> str:
        marker = "// GENERATED by vendor/nova/nova-framework/tools/sync-hybrid-framework.py"
        while marker in text:
            start = text.find(marker)
            fg = text.find("filegroup {", start)
            if fg < 0:
                break
            depth = 0
            i = fg
            while i < len(text):
                if text[i : i + 1] == "{":
                    depth += 1
                elif text[i : i + 1] == "}":
                    depth -= 1
                    if depth == 0:
                        i += 1
                        break
                i += 1
            text = text[:start] + text[i:]
        if NOVA_HYBRID_BEGIN in text and NOVA_HYBRID_END in text:
            begin = text.find(NOVA_HYBRID_BEGIN)
            end = text.find(NOVA_HYBRID_END)
            if end > begin:
                text = text[:begin] + text[end + len(NOVA_HYBRID_END) + 1 :]
        return text

    def splice_into_android_bp(path: Path, block: list[str]) -> None:
        text = strip_legacy_hybrid_blocks(path.read_text())
        block_text = NOVA_HYBRID_BEGIN + "\n" + "\n".join(block) + "\n" + NOVA_HYBRID_END + "\n"
        text = text.rstrip() + "\n\n" + block_text
        path.write_text(text)

    splice_into_android_bp(AOSP_CORE_BP, core_lines)
    splice_into_android_bp(AOSP_GRAPHICS_BP, graphics_lines)


def prune_shims(bridge_files: set[str], dry_run: bool) -> int:
    removed = 0
    aosp_relpaths = set(glob_aosp_sources())
    for path in sorted(SRC.rglob("*.java")):
        rel = path.relative_to(SRC).as_posix()
        if rel in bridge_files:
            continue
        if rel not in aosp_relpaths:
            continue
        if dry_run:
            print(f"would remove {rel}")
        else:
            path.unlink()
            removed += 1
    return removed


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--prune", action="store_true", help="Delete superseded shim files")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    bridge = load_bridge_files()
    aosp = glob_aosp_sources()
    write_aosp_bp(bridge, aosp)
    print(
        f"Wrote {AOSP_CORE_BP.name} and {AOSP_GRAPHICS_BP.name} "
        f"({len(aosp)} AOSP sources, {sum(1 for x in aosp if x in bridge)} excludes)"
    )

    if args.prune:
        n = prune_shims(bridge, args.dry_run)
        print(f"{'Would remove' if args.dry_run else 'Removed'} {n} shim files")


if __name__ == "__main__":
    main()
