#!/usr/bin/env python3
"""Prepare Nova hybrid framework: prune shim duplicates and emit Soong exclude_srcs."""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]
NOVA_FW = ROOT / "vendor/nova/nova-framework"
SRC = NOVA_FW / "src"
BRIDGE_LIST = NOVA_FW / "bridge_files.txt"
AOSP_CORE = ROOT / "frameworks/base/core/java"
AOSP_GRAPHICS = ROOT / "frameworks/base/graphics/java"
AOSP_CORE_BP = ROOT / "frameworks/base/core/java/Android.bp"
AOSP_GRAPHICS_BP = ROOT / "frameworks/base/graphics/java/Android.bp"
NOVA_HYBRID_BEGIN = "// NOVA_HYBRID_FILEGROUP_BEGIN"
NOVA_HYBRID_END = "// NOVA_HYBRID_FILEGROUP_END"

AOSP_PACKAGES = [
    ("core", AOSP_CORE, [
        "android/view/**/*.java",
        "android/widget/**/*.java",
        "android/text/**/*.java",
        "android/animation/**/*.java",
        "android/util/**/*.java",
        "android/database/**/*.java",
        "android/net/**/*.java",
        "android/provider/**/*.java",
        "android/preference/**/*.java",
        "android/window/**/*.java",
        "com/android/internal/util/**/*.java",
        "com/android/internal/view/menu/**/*.java",
    ]),
    ("graphics", AOSP_GRAPHICS, [
        "**/*.java",
    ]),
]


def load_bridge_files() -> set[str]:
    keep: set[str] = set()
    for line in BRIDGE_LIST.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        keep.add(line)
    return keep


def glob_aosp_sources() -> list[str]:
    import glob

    paths: list[str] = []
    for _name, base, patterns in AOSP_PACKAGES:
        if not base.is_dir():
            continue
        for pattern in patterns:
            for path in sorted(base.glob(pattern)):
                if path.suffix != ".java":
                    continue
                rel = path.relative_to(base).as_posix()
                paths.append(rel)
    return sorted(set(paths))


def write_aosp_bp(bridge_files: set[str], aosp_sources: list[str]) -> None:
    core_excludes = sorted(
        rel for rel in aosp_sources if rel in bridge_files and (AOSP_CORE / rel).is_file()
    )
    graphics_excludes = sorted(
        set(
            rel
            for rel in aosp_sources
            if rel in bridge_files and (AOSP_GRAPHICS / rel).is_file()
        )
        | {"android/graphics/HardwareRenderer.java"}
    )

    header = [
        "// GENERATED by vendor/nova/nova-framework/tools/sync-hybrid-framework.py",
        "// Filegroups must live under frameworks/base so Soong globs resolve to real .java files.",
        "",
    ]

    # Per-package slices — enable incrementally in nova-framework/Android.bp (hybrid-fork Step 4).
    # Subsystems we stub in src/ — exclude from AOSP view glob (hybrid-fork Step 2).
    VIEW_AOSP_EXCLUDES = [
        "android/view/accessibility/**/*.java",
        "android/view/autofill/**/*.java",
        "android/view/contentcapture/**/*.java",
        "android/view/contentprotection/**/*.java",
        "android/view/displayhash/**/*.java",
        "android/view/inputmethod/**/*.java",
        "android/view/selectiontoolbar/**/*.java",
        "android/view/textclassifier/**/*.java",
        "android/view/textservice/**/*.java",
        "android/view/translation/**/*.java",
        "android/view/inspector/**/*.java",
        "android/view/InputDevice.java",
        "android/view/InputWindowHandle.java",
        "android/view/InputChannel.java",
        "android/view/InputEvent.java",
        "android/view/InputMonitor.java",
        "android/view/InputQueue.java",
        "android/view/SurfaceView.java",
        # WMS / insets / display policy — Nova uses ViewRootImpl + Wayland, not AOSP WMS graph.
        "android/view/InsetsController.java",
        "android/view/InsetsAnimationControlImpl.java",
        "android/view/InsetsAnimationThreadControlRunner.java",
        "android/view/InsetsAnimationControlCallbacks.java",
        "android/view/InsetsAnimationControlRunner.java",
        "android/view/InsetsAnimationSpec.java",
        "android/view/InsetsAnimationThread.java",
        "android/view/InsetsSource.java",
        "android/view/InsetsSourceConsumer.java",
        "android/view/InsetsResizeAnimationRunner.java",
        "android/view/InsetsFlags.java",
        "android/view/InsetsFrameProvider.java",
        "android/view/InsetsState.java",
        "android/view/InsetsSourceControl.java",
        "android/view/PendingInsetsController.java",
        "android/view/InternalInsetsAnimationController.java",
        "android/view/WindowManagerImpl.java",
        "android/view/WindowManagerWrapper.java",
        "android/view/WindowManagerGlobal.java",
        "android/view/WindowManagerPolicyConstants.java",
        "android/view/WindowMetrics.java",
        "android/view/WindowMetricsController.java",
        "android/view/WindowRelayoutResult.java",
        "android/view/WindowLayout.java",
        "android/view/WindowlessWindowLayout.java",
        "android/view/WindowlessWindowManager.java",
        "android/view/AccessibilityInteractionController.java",
        "android/view/RemoteAccessibilityController.java",
        "android/view/RemoteAnimationAdapter.java",
        "android/view/RemoteAnimationDefinition.java",
        "android/view/RemoteAnimationTarget.java",
        "android/view/SyncRtSurfaceTransactionApplier.java",
        "android/view/ScrollCaptureConnection.java",
        "android/view/ScrollCaptureCallback.java",
        "android/view/ScrollCaptureResponse.java",
        "android/view/ScrollCaptureSearchResults.java",
        "android/view/ScrollCaptureSession.java",
        "android/view/ScrollCaptureTarget.java",
        "android/view/DisplayInfo.java",
        "android/view/DisplayShape.java",
        "android/view/DisplayCutout.java",
        "android/view/DisplayAddress.java",
        "android/view/DisplayAdjustments.java",
        "android/view/DisplayEventReceiver.java",
        "android/view/Display.java",
        "android/view/TextureView.java",
        "android/view/SurfaceControl.java",
        "android/view/SurfaceControlViewHost.java",
        "android/view/SurfaceSession.java",
        "android/view/SurfaceHolder.java",
        "android/view/HardwareRenderer.java",
        "android/view/ThreadedRenderer.java",
        "android/view/RenderNodeAnimator.java",
        "android/view/NativeVectorDrawableAnimator.java",
        "android/view/ImeBackAnimationController.java",
        "android/view/ImeFocusController.java",
        "android/view/HandwritingInitiator.java",
        "android/view/PixelCopy.java",
    ]

    INTERNAL_UTIL_EXTRA_EXCLUDES = [
        "com/android/internal/util/AnnotationValidations.java",
        "com/android/internal/util/LatencyTracker.java",
        "com/android/internal/util/ContrastColorUtil.java",
        "com/android/internal/util/XmlUtils.java",
        "com/android/internal/util/AsyncChannel.java",
    ]

    GRAPHICS_LITE_SRCS = [
        "android/graphics/RectF.java",
        "android/graphics/Point.java",
        "android/graphics/PointF.java",
        "android/graphics/Insets.java",
        "android/graphics/Matrix.java",
        "android/graphics/Region.java",
        "android/graphics/Outline.java",
        "android/graphics/RenderNode.java",
        "android/graphics/Color.java",
        "android/graphics/PorterDuff.java",
        "android/graphics/Typeface.java",
        "android/graphics/Shader.java",
        "android/graphics/Xfermode.java",
        "android/graphics/PixelFormat.java",
        "android/graphics/drawable/Drawable.java",
        "android/graphics/drawable/ColorDrawable.java",
        "android/graphics/drawable/BitmapDrawable.java",
        "android/graphics/drawable/GradientDrawable.java",
        "android/graphics/drawable/LayerDrawable.java",
        "android/graphics/drawable/StateListDrawable.java",
        "android/graphics/drawable/RippleDrawable.java",
        "android/graphics/drawable/VectorDrawable.java",
        "android/graphics/animation/HasNativeInterpolator.java",
        "android/graphics/animation/NativeInterpolator.java",
        "android/graphics/animation/NativeInterpolatorFactory.java",
        "android/graphics/animation/RenderNodeAnimator.java",
    ]

    SLICES = [
        ("nova-hybrid-animation-sources", ["android/animation/**/*.java"]),
        ("nova-hybrid-internal-util-sources", ["com/android/internal/util/**/*.java"]),
        ("nova-hybrid-internal-menu-sources", ["com/android/internal/view/menu/**/*.java"]),
        ("nova-hybrid-text-sources", ["android/text/**/*.java"]),
        ("nova-hybrid-widget-sources", ["android/widget/**/*.java"]),
        ("nova-hybrid-view-sources", ["android/view/**/*.java"]),
        ("nova-hybrid-window-sources", ["android/window/**/*.java"]),
        ("nova-hybrid-database-sources", ["android/database/**/*.java"]),
        ("nova-hybrid-net-sources", ["android/net/**/*.java"]),
        ("nova-hybrid-provider-sources", ["android/provider/**/*.java"]),
        ("nova-hybrid-preference-sources", ["android/preference/**/*.java"]),
        ("nova-hybrid-util-sources", ["android/util/**/*.java"]),
    ]

    def pattern_prefix(pattern: str) -> str:
        return pattern.split("*")[0].rstrip("/")

    def prefix_excludes(patterns: list[str]) -> list[str]:
        prefixes = [pattern_prefix(p) for p in patterns]
        out: list[str] = []
        for rel in core_excludes:
            if any(rel == p or rel.startswith(p + "/") for p in prefixes):
                out.append(rel)
        return sorted(out)

    def core_filegroup(name: str, patterns: list[str], excludes: list[str]) -> list[str]:
        lines = header + [
            "filegroup {",
            f'    name: "{name}",',
            '    visibility: ["//vendor:__subpackages__"],',
            "    srcs: [",
        ]
        for pattern in patterns:
            lines.append(f'        "{pattern}",')
        lines.extend(["    ],", "    exclude_srcs: ["])
        for rel in excludes:
            lines.append(f'        "{rel}",')
        lines.extend(["    ],", "}", ""])
        return lines

    core_lines: list[str] = []
    for slice_name, patterns in SLICES:
        excludes = prefix_excludes(patterns)
        if slice_name == "nova-hybrid-view-sources":
            excludes = sorted(set(excludes) | set(VIEW_AOSP_EXCLUDES))
        if slice_name == "nova-hybrid-internal-util-sources":
            excludes = sorted(set(excludes) | set(INTERNAL_UTIL_EXTRA_EXCLUDES))
        core_lines += core_filegroup(slice_name, patterns, excludes)

    graphics_lines = header + [
        "filegroup {",
        '    name: "nova-hybrid-graphics-sources",',
        '    visibility: ["//vendor:__subpackages__"],',
        '    srcs: ["**/*.java"],',
        "    exclude_srcs: [",
    ]
    for rel in graphics_excludes:
        graphics_lines.append(f'        "{rel}",')
    graphics_lines.extend(["    ],", "}", ""])
    graphics_lines += header + [
        "filegroup {",
        '    name: "nova-hybrid-graphics-lite-sources",',
        '    visibility: ["//vendor:__subpackages__"],',
        "    srcs: [",
    ]
    for rel in GRAPHICS_LITE_SRCS:
        graphics_lines.append(f'        "{rel}",')
    graphics_lite_excludes = [rel for rel in graphics_excludes if rel in GRAPHICS_LITE_SRCS]
    graphics_lines.extend(["    ],", "    exclude_srcs: ["])
    for rel in sorted(graphics_lite_excludes):
        graphics_lines.append(f'        "{rel}",')
    graphics_lines.extend(["    ],", "}", ""])

    def strip_legacy_hybrid_blocks(text: str) -> str:
        marker = "// GENERATED by vendor/nova/nova-framework/tools/sync-hybrid-framework.py"
        while marker in text:
            start = text.find(marker)
            fg = text.find("filegroup {", start)
            if fg < 0:
                break
            depth = 0
            i = fg
            while i < len(text):
                if text[i : i + 1] == "{":
                    depth += 1
                elif text[i : i + 1] == "}":
                    depth -= 1
                    if depth == 0:
                        i += 1
                        break
                i += 1
            text = text[:start] + text[i:]
        if NOVA_HYBRID_BEGIN in text and NOVA_HYBRID_END in text:
            begin = text.find(NOVA_HYBRID_BEGIN)
            end = text.find(NOVA_HYBRID_END)
            if end > begin:
                text = text[:begin] + text[end + len(NOVA_HYBRID_END) + 1 :]
        return text

    def splice_into_android_bp(path: Path, block: list[str]) -> None:
        text = strip_legacy_hybrid_blocks(path.read_text())
        block_text = NOVA_HYBRID_BEGIN + "\n" + "\n".join(block) + "\n" + NOVA_HYBRID_END + "\n"
        text = text.rstrip() + "\n\n" + block_text
        path.write_text(text)

    splice_into_android_bp(AOSP_CORE_BP, core_lines)
    splice_into_android_bp(AOSP_GRAPHICS_BP, graphics_lines)


def prune_shims(bridge_files: set[str], dry_run: bool) -> int:
    removed = 0
    aosp_relpaths = set(glob_aosp_sources())
    for path in sorted(SRC.rglob("*.java")):
        rel = path.relative_to(SRC).as_posix()
        if rel in bridge_files:
            continue
        if rel not in aosp_relpaths:
            continue
        if dry_run:
            print(f"would remove {rel}")
        else:
            path.unlink()
            removed += 1
    return removed


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--prune", action="store_true", help="Delete superseded shim files")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    bridge = load_bridge_files()
    aosp = glob_aosp_sources()
    write_aosp_bp(bridge, aosp)
    print(
        f"Wrote {AOSP_CORE_BP.name} and {AOSP_GRAPHICS_BP.name} "
        f"({len(aosp)} AOSP sources, {sum(1 for x in aosp if x in bridge)} excludes)"
    )

    if args.prune:
        n = prune_shims(bridge, args.dry_run)
        print(f"{'Would remove' if args.dry_run else 'Removed'} {n} shim files")


if __name__ == "__main__":
    main()
