#!/bin/bash
# Generate bionic_lib_path.h with the lib_path as a string constant
set -e
PREBUILT="/mnt/mydata/projects2/0/aosp-full/vendor/nova/aosp-prebuilt"
OUT_H="/mnt/mydata/projects2/0/aosp-full/vendor/nova/bionic-loader/bionic_lib_path.h"
OUT_ENV="/mnt/mydata/projects2/0/aosp-full/vendor/nova/bionic-loader/bionic_lib_path.env"
{
    printf '%s' "$PREBUILT/lib64"
    printf ':%s' "$PREBUILT/lib64/bootstrap"
    printf ':%s' "$PREBUILT/apex-flat/com.android.runtime/lib64/bionic"
    for d in "$PREBUILT/apex-flat"/*/lib64; do
        [ -d "$d" ] || continue
        bn=$(basename "$(dirname "$d")")
        case "$bn" in
            com.android.runtime) continue ;;
        esac
        printf ':%s' "$d"
    done
} > "$OUT_ENV"

# Now generate the header — keep the C string on one line
ESCAPED=$(sed 's/["\\]/\\&/g' "$OUT_ENV")
{
    echo '/* Auto-generated by gen_lib_path.sh - do not edit. */'
    echo '#ifndef NOVA_BIONIC_LIB_PATH_H'
    echo '#define NOVA_BIONIC_LIB_PATH_H'
    printf 'static const char NOVA_BIONIC_LIB_PATH[] = "%s";\n' "$ESCAPED"
    echo '#endif'
} > "$OUT_H"
echo "Wrote $OUT_H and $OUT_ENV"
